// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.6
// source: proto/jobgen.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the crawler url
type CrawlerJobRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *CrawlerJobRequest) Reset() {
	*x = CrawlerJobRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_jobgen_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CrawlerJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrawlerJobRequest) ProtoMessage() {}

func (x *CrawlerJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jobgen_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrawlerJobRequest.ProtoReflect.Descriptor instead.
func (*CrawlerJobRequest) Descriptor() ([]byte, []int) {
	return file_proto_jobgen_proto_rawDescGZIP(), []int{0}
}

func (x *CrawlerJobRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// The response message containing the crawler reply
type CrawlerJobReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *CrawlerJobReply) Reset() {
	*x = CrawlerJobReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_jobgen_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CrawlerJobReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrawlerJobReply) ProtoMessage() {}

func (x *CrawlerJobReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jobgen_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrawlerJobReply.ProtoReflect.Descriptor instead.
func (*CrawlerJobReply) Descriptor() ([]byte, []int) {
	return file_proto_jobgen_proto_rawDescGZIP(), []int{1}
}

func (x *CrawlerJobReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// A chatter request, represented as single requesting name
type ChatterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ChatterRequest) Reset() {
	*x = ChatterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_jobgen_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatterRequest) ProtoMessage() {}

func (x *ChatterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jobgen_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatterRequest.ProtoReflect.Descriptor instead.
func (*ChatterRequest) Descriptor() ([]byte, []int) {
	return file_proto_jobgen_proto_rawDescGZIP(), []int{2}
}

func (x *ChatterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// A chatter simulates a ongoing one way text stream
type Chatter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The name of the chatter requester.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The simulated chatter
	Chatter string `protobuf:"bytes,2,opt,name=chatter,proto3" json:"chatter,omitempty"`
}

func (x *Chatter) Reset() {
	*x = Chatter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_jobgen_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Chatter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chatter) ProtoMessage() {}

func (x *Chatter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jobgen_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chatter.ProtoReflect.Descriptor instead.
func (*Chatter) Descriptor() ([]byte, []int) {
	return file_proto_jobgen_proto_rawDescGZIP(), []int{3}
}

func (x *Chatter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Chatter) GetChatter() string {
	if x != nil {
		return x.Chatter
	}
	return ""
}

var File_proto_jobgen_proto protoreflect.FileDescriptor

var file_proto_jobgen_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6a, 0x6f, 0x62, 0x67, 0x65, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x25, 0x0a, 0x11, 0x43,
	0x72, 0x61, 0x77, 0x6c, 0x65, 0x72, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75,
	0x72, 0x6c, 0x22, 0x2b, 0x0a, 0x0f, 0x43, 0x72, 0x61, 0x77, 0x6c, 0x65, 0x72, 0x4a, 0x6f, 0x62,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22,
	0x24, 0x0a, 0x0e, 0x43, 0x68, 0x61, 0x74, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x37, 0x0a, 0x07, 0x43, 0x68, 0x61, 0x74, 0x74, 0x65, 0x72,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x74, 0x74, 0x65, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x68, 0x61, 0x74, 0x74, 0x65, 0x72, 0x32, 0x8e,
	0x01, 0x0a, 0x06, 0x4a, 0x6f, 0x62, 0x47, 0x65, 0x6e, 0x12, 0x48, 0x0a, 0x12, 0x47, 0x65, 0x6e,
	0x65, 0x72, 0x61, 0x74, 0x65, 0x43, 0x72, 0x61, 0x77, 0x6c, 0x65, 0x72, 0x4a, 0x6f, 0x62, 0x12,
	0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x72, 0x61, 0x77, 0x6c, 0x65, 0x72, 0x4a,
	0x6f, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x43, 0x72, 0x61, 0x77, 0x6c, 0x65, 0x72, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x0d, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x43, 0x68, 0x61,
	0x74, 0x74, 0x65, 0x72, 0x12, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x68, 0x61,
	0x74, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x74, 0x65, 0x72, 0x22, 0x00, 0x30, 0x01, 0x42,
	0x37, 0x5a, 0x35, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x65,
	0x64, 0x6f, 0x72, 0x62, 0x2f, 0x6b, 0x38, 0x73, 0x2d, 0x70, 0x6c, 0x61, 0x79, 0x67, 0x72, 0x6f,
	0x75, 0x6e, 0x64, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x61, 0x70, 0x69, 0x2d, 0x69, 0x6e, 0x67, 0x65,
	0x73, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_jobgen_proto_rawDescOnce sync.Once
	file_proto_jobgen_proto_rawDescData = file_proto_jobgen_proto_rawDesc
)

func file_proto_jobgen_proto_rawDescGZIP() []byte {
	file_proto_jobgen_proto_rawDescOnce.Do(func() {
		file_proto_jobgen_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_jobgen_proto_rawDescData)
	})
	return file_proto_jobgen_proto_rawDescData
}

var file_proto_jobgen_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_jobgen_proto_goTypes = []interface{}{
	(*CrawlerJobRequest)(nil), // 0: proto.CrawlerJobRequest
	(*CrawlerJobReply)(nil),   // 1: proto.CrawlerJobReply
	(*ChatterRequest)(nil),    // 2: proto.ChatterRequest
	(*Chatter)(nil),           // 3: proto.Chatter
}
var file_proto_jobgen_proto_depIdxs = []int32{
	0, // 0: proto.JobGen.GenerateCrawlerJob:input_type -> proto.CrawlerJobRequest
	2, // 1: proto.JobGen.StreamChatter:input_type -> proto.ChatterRequest
	1, // 2: proto.JobGen.GenerateCrawlerJob:output_type -> proto.CrawlerJobReply
	3, // 3: proto.JobGen.StreamChatter:output_type -> proto.Chatter
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_jobgen_proto_init() }
func file_proto_jobgen_proto_init() {
	if File_proto_jobgen_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_jobgen_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CrawlerJobRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_jobgen_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CrawlerJobReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_jobgen_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_jobgen_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Chatter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_jobgen_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_jobgen_proto_goTypes,
		DependencyIndexes: file_proto_jobgen_proto_depIdxs,
		MessageInfos:      file_proto_jobgen_proto_msgTypes,
	}.Build()
	File_proto_jobgen_proto = out.File
	file_proto_jobgen_proto_rawDesc = nil
	file_proto_jobgen_proto_goTypes = nil
	file_proto_jobgen_proto_depIdxs = nil
}
